name: lefrigo
description: Final project
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  camera: ^0.10.5+4
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  fpdart: ^1.1.0
  get_it: ^7.6.4
  google_fonts: ^5.1.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  provider: ^6.0.5
  intl: ^0.17.0
  country_picker: ^2.0.21
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
