name: cs426final
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  country_picker: ^2.0.21
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android_12:
    color: "#ffffff"
    image: assets/logo.png
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
