name: cs426final
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  country_picker: ^2.0.21
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android_12:
    color: "#ffffff"
    image: assets/logo.png
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
