name: cs426final
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.5
  intl: ^0.17.0
  country_picker: ^2.0.21
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1

flutter:
  uses-material-design: true

assets:
    - assets/welcomeImg1.svg
    - assets/logo.svg
    - assets/welcomeImg.png
    - assets/decor1.svg
    - assets/google.svg
    - assets/google.png
    - assets/food.png
