// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfx4fRsp24lDcgAb-3r86DQ2Jb6YxnDUc',
    appId: '1:11763551091:android:5f063e0598039f50511306',
    messagingSenderId: '11763551091',
    projectId: 'recipe-app-57f2c',
    storageBucket: 'recipe-app-57f2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpF8OljSzpg3TYYHlTuIL-QxLzr0yoYo',
    appId: '1:11763551091:ios:57ac1c5166525ce4511306',
    messagingSenderId: '11763551091',
    projectId: 'recipe-app-57f2c',
    storageBucket: 'recipe-app-57f2c.appspot.com',
    iosClientId:
        '11763551091-d390494k74v10gckksgh6h7etagkstqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.leFrigo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmpF8OljSzpg3TYYHlTuIL-QxLzr0yoYo',
    authDomain: 'recipe-app-57f2c.firebaseapp.com',
    databaseURL:
        'https://recipe-app-57f2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'recipe-app-57f2c',
    storageBucket: 'recipe-app-57f2c.appspot.com',
    messagingSenderId: '11763551091',
    appId: '1:11763551091:ios:57ac1c5166525ce4511306',
  );
}
